
services:
  app:
    image: wanderlust-dev
    build:
      context: .
    container_name: wanderlust-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_AUTH_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_AUTH_PASSWORD}
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -Xms256m  # Match Dockerfile JVM settings
    networks:
      - app-network
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
#      interval: 30s
#      timeout: 5s
#      retries: 3

  db:
    image: postgres:15-alpine
    container_name: wanderlust-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_AUTH_USERNAME}
      - POSTGRES_PASSWORD=${DB_AUTH_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_AUTH_USERNAME} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/pg-data  # Uses current directory
      o: bind

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16  # Isolated network