spring:
  application:
    name: WanderLustAPI
server:
  servlet:
    context-path: /api/v1/

logging:
  level:
    org.springframework.security: trace

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

